# Generated by Django 3.0.8 on 2020-07-18 16:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('demands', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demanda',
            name='atribuicao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='demanda',
            name='canal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='demands.Canal'),
        ),
        migrations.RemoveField(
            model_name='demanda',
            name='demandante',
        ),
        migrations.AddField(
            model_name='demanda',
            name='demandante',
            field=models.ManyToManyField(blank=True, to='demands.Demandante'),
        ),
    ]
