# Generated by Django 3.0.8 on 2020-07-18 19:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('demands', '0003_auto_20200718_1351'),
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_name', models.CharField(blank=True, max_length=25, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Demand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_date', models.DateField(blank=True, null=True, verbose_name='Data da solicitação')),
                ('completion_date', models.DateField(blank=True, null=True, verbose_name='Data da conclusão')),
                ('demand', models.TextField(verbose_name='Demanda')),
                ('image', models.ImageField(blank=True, null=True, upload_to='demandas_photos')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Observação')),
                ('effective_date_completion', models.DateField(blank=True, null=True, verbose_name='Data efetiva da conclusão')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='demands.Channel')),
            ],
        ),
        migrations.CreateModel(
            name='Demandant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('demandant_name', models.CharField(blank=True, max_length=25, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='demanda',
            name='atribuicao',
        ),
        migrations.RemoveField(
            model_name='demanda',
            name='canal',
        ),
        migrations.RemoveField(
            model_name='demanda',
            name='demandante',
        ),
        migrations.DeleteModel(
            name='Canal',
        ),
        migrations.DeleteModel(
            name='Demanda',
        ),
        migrations.DeleteModel(
            name='Demandante',
        ),
        migrations.AddField(
            model_name='demand',
            name='demandant',
            field=models.ManyToManyField(blank=True, to='demands.Demandant'),
        ),
    ]
