# Generated by Django 3.0.8 on 2020-07-18 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demands', '0004_auto_20200718_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demand',
            name='completion_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='demand',
            name='demand',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='demand',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='demand',
            name='request_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
